name: Release A Version

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "appimage continious.yml"
          workflow_conclusion: success
          path: artifacts
      - name: Make Draft Release
        uses: softprops/action-gh-release@v1
        with:
          name: Znax Vx.x
          draft: true
          files: |
            artifacts/AppImage/*.AppImage*